# project_generator.py
# developer: SuperHeroPuppy
# version: 1.0.0

from __future__ import annotations

import importlib.util
import json
import re
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Callable


GENERATORS_ROOT = Path(__file__).resolve().parent.parent / "generators"


@dataclass
class ProjectData:
    name: str
    minecraft_version: str
    fabric_version: str
    author: str
    mod_id: str
    package_root: str = "com"
    package_name: str = ""
    description: str = "A Fabric mod generated by Fabric Studio."
    loader: str = "fabric"
    generator_id: str = ""


@dataclass(frozen=True)
class GeneratorSpec:
    id: str
    name: str
    minecraft_version: str
    loader: str
    loader_versions: list[str]
    generator_version: str
    root: Path
    module: str = "generator.py"
    callable_name: str = "generate_project"
    description: str = ""

    @property
    def script_path(self) -> Path:
        return self.root / self.module


class ProjectGenerator:
    """Discovers and runs versioned project generator packages."""

    def __init__(self, workspace_root: Path, generators_root: Path | None = None) -> None:
        self.workspace_root = workspace_root
        self.generators_root = generators_root or GENERATORS_ROOT

    def generate(self, data: ProjectData) -> Path:
        self._validate_common(data)
        spec = self._select_generator(data)
        self._validate_generator_data(data, spec)
        module = self._load_module(spec)
        generate_project = self._get_generate_callable(module, spec)

        result = generate_project(data, self.workspace_root, spec)

        return result

    def _validate_common(self, data: ProjectData) -> None:
        if not data.name.strip():
            raise ValueError("Project name is required.")
        if not re.fullmatch(r"[a-z][a-z0-9_]{1,63}", data.mod_id):
            raise ValueError("Mod ID must be lowercase and may contain numbers or underscores.")
        if not re.fullmatch(r"[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*", data.package_root):
            raise ValueError("Package root must look like com or net.example.")
        if data.package_name and not re.fullmatch(r"[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*", data.package_name):
            raise ValueError("Package name must be lowercase and may use dots or underscores.")
        if not data.package_name:
            data.package_name = data.mod_id
        data.loader = data.loader.strip().lower() or "fabric"
        if data.loader == "fabric" and not data.fabric_version.strip():
            raise ValueError("Fabric loader version is required.")

    def _validate_generator_data(self, data: ProjectData, spec: GeneratorSpec) -> None:
        if data.loader == "fabric" and spec.loader_versions and data.fabric_version not in spec.loader_versions:
            raise ValueError(
                f"Fabric loader {data.fabric_version} is not supported by generator '{spec.id}'."
            )

    def _select_generator(self, data: ProjectData) -> GeneratorSpec:
        specs = list(iter_generator_specs(self.generators_root))
        if data.generator_id:
            for spec in specs:
                if spec.id == data.generator_id:
                    return spec
            raise ValueError(f"Generator '{data.generator_id}' is not installed.")

        matches = [
            spec
            for spec in specs
            if spec.minecraft_version == data.minecraft_version
            and spec.loader.lower() == data.loader
        ]
        if not matches:
            folder_name = f"{data.minecraft_version}-{data.loader}-generator-1.0.0"
            raise ValueError(
                f"No {data.loader} generator is installed for Minecraft {data.minecraft_version}. "
                f"Add one under generators/{folder_name}."
            )
        return sorted(matches, key=lambda item: item.generator_version, reverse=True)[0]

    def _load_module(self, spec: GeneratorSpec) -> ModuleType:
        if not spec.script_path.exists():
            raise ValueError(f"Generator '{spec.id}' is missing {spec.module}.")

        module_name = "_fabricstudio_generator_" + re.sub(r"[^a-zA-Z0-9_]", "_", spec.id)
        module_spec = importlib.util.spec_from_file_location(module_name, spec.script_path)
        if module_spec is None or module_spec.loader is None:
            raise ValueError(f"Could not load generator '{spec.id}'.")

        module = importlib.util.module_from_spec(module_spec)
        module_spec.loader.exec_module(module)
        return module

    def _get_generate_callable(
        self,
        module: ModuleType,
        spec: GeneratorSpec,
    ) -> Callable[[ProjectData, Path, GeneratorSpec], Path]:
        generate_project = getattr(module, spec.callable_name, None)
        if not callable(generate_project):
            raise ValueError(f"Generator '{spec.id}' does not define {spec.callable_name}().")
        return generate_project


def iter_generator_specs(generators_root: Path = GENERATORS_ROOT) -> list[GeneratorSpec]:
    if not generators_root.exists():
        return []

    specs: list[GeneratorSpec] = []
    for manifest_path in sorted(generators_root.glob("*/manifest.json")):
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            root = manifest_path.parent
            specs.append(
                GeneratorSpec(
                    id=str(manifest.get("id") or root.name),
                    name=str(manifest.get("name") or root.name),
                    minecraft_version=str(manifest["minecraft_version"]),
                    loader=str(manifest["loader"]).lower(),
                    loader_versions=[str(version) for version in manifest.get("loader_versions", [])],
                    generator_version=str(manifest.get("generator_version") or "0.0.0"),
                    root=root,
                    module=str(manifest.get("module") or "generator.py"),
                    callable_name=str(manifest.get("callable") or "generate_project"),
                    description=str(manifest.get("description") or ""),
                )
            )
        except (OSError, json.JSONDecodeError, KeyError):
            continue
    return specs


def get_available_generators(loader: str | None = None) -> list[GeneratorSpec]:
    specs = list(iter_generator_specs())
    if loader:
        loader = loader.lower()
        specs = [spec for spec in specs if spec.loader == loader]
    return specs


def get_supported_minecraft_versions(loader: str = "fabric") -> list[str]:
    seen: set[str] = set()
    versions: list[str] = []
    for spec in get_available_generators(loader):
        if spec.minecraft_version in seen:
            continue
        seen.add(spec.minecraft_version)
        versions.append(spec.minecraft_version)
    return versions

