from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path


@dataclass
class ProjectData:
    name: str
    minecraft_version: str
    fabric_version: str
    author: str
    mod_id: str
    package_root: str = "com"
    package_name: str = ""
    description: str = "A Fabric mod generated by Fabric Studio."


class ProjectGenerator:
    """Creates the first supported Fabric project template: Minecraft 1.20.1."""

    supported_minecraft_version = "1.20.1"

    def __init__(self, workspace_root: Path) -> None:
        self.workspace_root = workspace_root

    def generate(self, data: ProjectData) -> Path:
        self._validate(data)

        project_path = self.workspace_root / data.name
        package_path = Path(*self._package_parts(data))
        java_root = project_path / "src" / "main" / "java" / package_path
        resources_root = project_path / "src" / "main" / "resources"

        java_root.mkdir(parents=True, exist_ok=True)
        resources_root.mkdir(parents=True, exist_ok=True)

        self._write(project_path / "settings.gradle", self._settings_gradle(data))
        self._write(project_path / "build.gradle", self._build_gradle(data))
        self._write(project_path / "gradle.properties", self._gradle_properties(data))
        self._write(resources_root / "fabric.mod.json", self._fabric_mod_json(data))
        self._write(java_root / f"{self._class_name(data.mod_id)}.java", self._main_class(data))
        self._write(project_path / "project_info.json", self._project_info(data))

        return project_path

    def _validate(self, data: ProjectData) -> None:
        if not data.name.strip():
            raise ValueError("Project name is required.")
        if not re.fullmatch(r"[a-z][a-z0-9_]{1,63}", data.mod_id):
            raise ValueError("Mod ID must be lowercase and may contain numbers or underscores.")
        if not re.fullmatch(r"[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*", data.package_root):
            raise ValueError("Package root must look like com or net.example.")
        if data.package_name and not re.fullmatch(r"[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*", data.package_name):
            raise ValueError("Package name must be lowercase and may use dots or underscores.")
        if data.minecraft_version != self.supported_minecraft_version:
            raise ValueError("Generator support currently starts with Minecraft 1.20.1.")
        if not data.package_name:
            data.package_name = data.mod_id

    def _write(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content.strip() + "\n", encoding="utf-8")

    def _settings_gradle(self, data: ProjectData) -> str:
        return f"""
pluginManagement {{
    repositories {{
        maven {{ url = 'https://maven.fabricmc.net/' }}
        gradlePluginPortal()
    }}
}}

dependencyResolutionManagement {{
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {{
        maven {{ url = 'https://maven.fabricmc.net/' }}
        mavenCentral()
    }}
}}

rootProject.name = '{data.name}'
"""

    def _build_gradle(self, data: ProjectData) -> str:
        return """
plugins {
    id 'fabric-loom' version '1.6-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
}
"""

    def _gradle_properties(self, data: ProjectData) -> str:
        group_name = self._package_declaration(data)
        return f"""
org.gradle.jvmargs=-Xmx1G
minecraft_version={data.minecraft_version}
yarn_mappings=1.20.1+build.10
loader_version={data.fabric_version}
mod_version=1.0.0
maven_group={group_name}
archives_base_name={data.mod_id}
"""

    def _fabric_mod_json(self, data: ProjectData) -> str:
        package_name = self._package_declaration(data)
        payload = {
            "schemaVersion": 1,
            "id": data.mod_id,
            "version": "${version}",
            "name": data.name,
            "description": data.description,
            "authors": [data.author or "Unknown"],
            "environment": "*",
            "entrypoints": {"main": [f"{package_name}.{self._class_name(data.mod_id)}"]},
            "depends": {"fabricloader": f">={data.fabric_version}", "minecraft": data.minecraft_version, "java": ">=17"},
        }
        return json.dumps(payload, indent=2)

    def _main_class(self, data: ProjectData) -> str:
        class_name = self._class_name(data.mod_id)
        package_name = self._package_declaration(data)
        return f"""
package {package_name};

import net.fabricmc.api.ModInitializer;

public class {class_name} implements ModInitializer {{
    @Override
    public void onInitialize() {{
        System.out.println("{data.name} loaded.");
    }}
}}
"""

    def _project_info(self, data: ProjectData) -> str:
        payload = asdict(data)
        payload["created_at"] = datetime.now().isoformat(timespec="seconds")
        return json.dumps(payload, indent=2)

    def _class_name(self, mod_id: str) -> str:
        return "".join(part.capitalize() for part in mod_id.split("_")) + "Mod"

    def _package_parts(self, data: ProjectData) -> list[str]:
        package_name = data.package_name or data.mod_id
        return data.package_root.split(".") + package_name.split(".")

    def _package_declaration(self, data: ProjectData) -> str:
        return ".".join(self._package_parts(data))
